version: "3"
services:
    webserver:
      build:
        context: .
        dockerfile: Dockerfile_Nginx
      image: bitnami/nginx
      container_name: nginx
      restart: always
      working_dir: /usr/share/nginx/html
      user: root
      ports:
      - 80:80
      networks:
      - ci-network
    jenkins:
      depends_on:
       - webserver
      image: jenkins/jenkins:lts-jdk11
      ports:
      - 8080:8080
      - 50000:50000
      container_name: jenkins
      volumes:
      - /Users/mubashira/Documents/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      networks:
      - ci-network

#Docker Networks
networks:
  ci-network:
    driver: bridge