FROM nginx:latest

RUN apt-get update && apt-get install -y \
    certbot \
    python3-certbot-nginx \
    net-tools \
    vim procps \
    && rm -f /etc/nginx/nginx.conf \
    && rm -f /etc/nginx/conf.d/default.conf \
    && mkdir -p /var/www/html \
    && chown -R nginx:nginx /var/www/html/

COPY nginx/conf.d/default.conf /etc/nginx/conf.d/
COPY nginx/conf.d/gzip.conf /etc/nginx/conf.d/
COPY nginx/conf.d/secconfig.conf /etc/nginx/conf.d/
COPY nginx/conf/nginx.conf /etc/nginx/
COPY nginx/index.html /var/wwww/html/

#Expose Nginx Port
EXPOSE 80

#Start NginxService 
CMD ["nginx", "-g", "daemon off;"]